name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Instalar Dependências
        run: npm install

      - name: Snake Game
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: YagoASantos
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # Use a versão estável mais recente
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
